### ISSUE TITLE
Compiling with musl target

### ISSUE THREAD

**Issue by jeromegn** [jbaublitz/neli#33] opened 2019-07-23 17:38 UTC
Trying to add neli to a project using the musl target yields 59 errors. All missing constants:

I'm not sure if this is fixable. Sounds like they need to be added to libc for musl specifically. They might have been removed at some point (rust-lang/libc#922).

```
error[E0425]: cannot find value `NLA_ALIGNTO` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:212:18
    |
212 |     (len + libc::NLA_ALIGNTO as usize - 1) & !(libc::NLA_ALIGNTO as usize - 1)
    |                  ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLA_ALIGNTO` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:212:54
    |
212 |     (len + libc::NLA_ALIGNTO as usize - 1) & !(libc::NLA_ALIGNTO as usize - 1)
    |                                                      ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `IFA_F_MANAGETEMPADDR` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:250:29
    |
250 |     Managetempaddr => libc::IFA_F_MANAGETEMPADDR,
    |                             ^^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `IFA_F_NOPREFIXROUTE` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:251:28
    |
251 |     Noprefixroute => libc::IFA_F_NOPREFIXROUTE,
    |                            ^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `IFA_F_MCAUTOJOIN` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:252:25
    |
252 |     Mcautojoin => libc::IFA_F_MCAUTOJOIN,
    |                         ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `IFA_F_STABLE_PRIVACY` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:253:28
    |
253 |     StablePrivacy => libc::IFA_F_STABLE_PRIVACY
    |                            ^^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `RTM_F_LOOKUP_TABLE` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:315:26
    |
315 |     LookupTable => libc::RTM_F_LOOKUP_TABLE,
    |                          ^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `RTM_F_FIB_MATCH` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:316:23
    |
316 |     FibMatch => libc::RTM_F_FIB_MATCH
    |                       ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NTF_EXT_LEARNED` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:340:25
    |
340 |     ExtLearned => libc::NTF_EXT_LEARNED,
    |                         ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NTF_OFFLOADED` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:341:24
    |
341 |     Offloaded => libc::NTF_OFFLOADED,
    |                        ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `IFA_FLAGS` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:374:20
    |
374 |     Flags => libc::IFA_FLAGS
    |                    ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `RTA_VIA` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:399:18
    |
399 |     Via => libc::RTA_VIA,
    |                  ^^^^^^^ help: a constant with a similar name exists: `RTA_IIF`

error[E0425]: cannot find value `RTA_NEWDST` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:400:21
    |
400 |     Newdst => libc::RTA_NEWDST,
    |                     ^^^^^^^^^^ help: a constant with a similar name exists: `RTA_DST`

error[E0425]: cannot find value `RTA_PREF` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:401:19
    |
401 |     Pref => libc::RTA_PREF,
    |                   ^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `RTA_ENCAP_TYPE` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:402:24
    |
402 |     EncapType => libc::RTA_ENCAP_TYPE,
    |                        ^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `RTA_ENCAP` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:403:20
    |
403 |     Encap => libc::RTA_ENCAP,
    |                    ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `RTA_EXPIRES` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:404:22
    |
404 |     Expires => libc::RTA_EXPIRES,
    |                      ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `RTA_PAD` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:405:18
    |
405 |     Pad => libc::RTA_PAD,
    |                  ^^^^^^^ not found in `libc`

error[E0425]: cannot find value `RTA_UID` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:406:18
    |
406 |     Uid => libc::RTA_UID,
    |                  ^^^^^^^ help: a constant with a similar name exists: `RTA_IIF`

error[E0425]: cannot find value `RTA_TTL_PROPAGATE` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:407:27
    |
407 |     TtlPropagate => libc::RTA_TTL_PROPAGATE
    |                           ^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_ROUTE` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:479:20
    |
479 |     Route => libc::NETLINK_ROUTE,
    |                    ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_UNUSED` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:480:21
    |
480 |     Unused => libc::NETLINK_UNUSED,
    |                     ^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_USERSOCK` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:481:23
    |
481 |     Usersock => libc::NETLINK_USERSOCK,
    |                       ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_FIREWALL` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:482:23
    |
482 |     Firewall => libc::NETLINK_FIREWALL,
    |                       ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_SOCK_DIAG` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:483:29
    |
483 |     SockOrInetDiag => libc::NETLINK_SOCK_DIAG,
    |                             ^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_NFLOG` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:484:20
    |
484 |     Nflog => libc::NETLINK_NFLOG,
    |                    ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_XFRM` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:485:19
    |
485 |     Xfrm => libc::NETLINK_XFRM,
    |                   ^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_SELINUX` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:486:22
    |
486 |     Selinux => libc::NETLINK_SELINUX,
    |                      ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_ISCSI` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:487:20
    |
487 |     Iscsi => libc::NETLINK_ISCSI,
    |                    ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_AUDIT` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:488:20
    |
488 |     Audit => libc::NETLINK_AUDIT,
    |                    ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_FIB_LOOKUP` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:489:24
    |
489 |     FibLookup => libc::NETLINK_FIB_LOOKUP,
    |                        ^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_CONNECTOR` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:490:24
    |
490 |     Connector => libc::NETLINK_CONNECTOR,
    |                        ^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_NETFILTER` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:491:24
    |
491 |     Netfilter => libc::NETLINK_NETFILTER,
    |                        ^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_IP6_FW` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:492:20
    |
492 |     Ip6Fw => libc::NETLINK_IP6_FW,
    |                    ^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_DNRTMSG` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:493:22
    |
493 |     Dnrtmsg => libc::NETLINK_DNRTMSG,
    |                      ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_KOBJECT_UEVENT` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:494:28
    |
494 |     KobjectUevent => libc::NETLINK_KOBJECT_UEVENT,
    |                            ^^^^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_GENERIC` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:495:22
    |
495 |     Generic => libc::NETLINK_GENERIC,
    |                      ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_SCSITRANSPORT` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:496:28
    |
496 |     Scsitransport => libc::NETLINK_SCSITRANSPORT,
    |                            ^^^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_ECRYPTFS` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:497:23
    |
497 |     Ecryptfs => libc::NETLINK_ECRYPTFS,
    |                       ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_RDMA` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:498:19
    |
498 |     Rdma => libc::NETLINK_RDMA,
    |                   ^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NETLINK_CRYPTO` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:499:21
    |
499 |     Crypto => libc::NETLINK_CRYPTO
    |                     ^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `GENL_ID_VFS_DQUOT` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:522:23
    |
522 |     VfsDquot => libc::GENL_ID_VFS_DQUOT as u16,
    |                       ^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `GENL_ID_PMCRAID` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:523:22
    |
523 |     Pmcraid => libc::GENL_ID_PMCRAID as u16
    |                      ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_REQUEST` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:529:22
    |
529 |     Request => libc::NLM_F_REQUEST as u16,
    |                      ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_MULTI` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:530:20
    |
530 |     Multi => libc::NLM_F_MULTI as u16,
    |                    ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_ACK` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:531:18
    |
531 |     Ack => libc::NLM_F_ACK as u16,
    |                  ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_ECHO` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:532:19
    |
532 |     Echo => libc::NLM_F_ECHO as u16,
    |                   ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_DUMP_INTR` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:533:23
    |
533 |     DumpIntr => libc::NLM_F_DUMP_INTR as u16,
    |                       ^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_DUMP_FILTERED` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:534:27
    |
534 |     DumpFiltered => libc::NLM_F_DUMP_FILTERED as u16,
    |                           ^^^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_ROOT` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:535:19
    |
535 |     Root => libc::NLM_F_ROOT as u16,
    |                   ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_MATCH` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:536:20
    |
536 |     Match => libc::NLM_F_MATCH as u16,
    |                    ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_ATOMIC` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:537:21
    |
537 |     Atomic => libc::NLM_F_ATOMIC as u16,
    |                     ^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_DUMP` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:538:19
    |
538 |     Dump => libc::NLM_F_DUMP as u16,
    |                   ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_REPLACE` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:539:22
    |
539 |     Replace => libc::NLM_F_REPLACE as u16,
    |                      ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_EXCL` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:540:19
    |
540 |     Excl => libc::NLM_F_EXCL as u16,
    |                   ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_CREATE` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:541:21
    |
541 |     Create => libc::NLM_F_CREATE as u16,
    |                     ^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `NLM_F_APPEND` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/consts.rs:542:21
    |
542 |     Append => libc::NLM_F_APPEND as u16
    |                     ^^^^^^^^^^^^ help: a constant with a similar name exists: `GLOB_APPEND`

error[E0425]: cannot find value `NETLINK_ADD_MEMBERSHIP` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/socket.rs:145:36
    |
145 |                              libc::NETLINK_ADD_MEMBERSHIP,
    |                                    ^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `IP_ADD_MEMBERSHIP`

error[E0425]: cannot find value `NLA_ALIGNTO` in module `libc`
   --> /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/neli-0.4.2/src/nlattr.rs:162:44
    |
162 |             let padding = &mut [0u8; libc::NLA_ALIGNTO as usize][0..padding_len];
    |                                            ^^^^^^^^^^^ not found in `libc`

error: aborting due to 59 previous errors
```

**Comment by jbaublitz** [comment] 2019-07-24 00:17
Just took a look and you were right on the libc issue. This does seem to be missing from the general module. I'll make a PR to libc and link back here. Thanks for the report!

**Comment by jbaublitz** [comment] 2019-07-27 17:24
I'm still investigating a bit. I'm doing this in two phases. One is libc support for netlink musl constants but the next phase will be looking at my own code and making sure I don't include any glibc specific constants in my enums. What I'm considering is adding them in in a separate issue and feature flagging them based on target so that it doesn't break musl. I'll keep you posted.

**Comment by jeromegn** [comment] 2019-07-27 18:16
Awesome. Thanks for looking into it for me!

**Comment by jbaublitz** [comment] 2019-08-03 15:56
Update: CI is not passing on libc because there's a bug in nightly with a fix that seems to have been merged. I'm going to try to put together CI in neli for a musl target now so that I can make sure there's no breakage moving forward. rust-lang/libc#1452 is the PR with the work I've done so far for reference.

**Comment by jbaublitz** [comment] 2019-08-07 00:23
I updated my CI on master and have [reproduced your pasted errors](https://travis-ci.org/jbaublitz/neli/jobs/568617975#L521). I'm going to see if libc CI is working again in the next few days and try to get this fixed upstream. Thanks for your patience!

**Comment by jbaublitz** [comment] 2019-08-08 22:57
I think I've fixed this on master - CI is in place, I'm pointing at my fork of libc for the constants that have not been migrated between modules upstream yet, and I've edited macros to pass through flags disabling the GNU-specific constants. I'll wait until tests pass in CI, but based on local testing, this seems to be resolved. Can you give it a try too before I close this out?

**Comment by jbaublitz** [comment] 2019-08-10 13:56
Closing. Post here if it's not fixed.

**Closed by jbaublitz** 2019-08-10 13:56 UTC
Labels: personal project

**Comment by jeromegn** [comment] 2019-08-12 14:22
Appears to work great! Thanks.

Looks like libc was bumped Today, it might include your changes.
