### ISSUE TITLE
Nlattr construction payloads should pad to a multiple of NLMSG_ALIGNTO bytes

### ISSUE THREAD

**Issue by gluxon** [jbaublitz/neli#17] opened 2019-04-29 19:38 UTC
Hey John, I want to avoid piling a bunch of issues on you, so please feel free to ignore this if you're busy. I had some protocol errors and discovered this as the cause and just wanted to file it somewhere. I think the fix is easy, so I'll do a pull request myself within a few weeks.

I think `NlAttrHdr` payload construction methods should be padding aware. To [quote libnl](http://www.infradead.org/~tgr/libnl/doc/core.html#_message_format):

> Most netlink protocols enforce a strict alignment policy for all boundries. The alignment value is defined by NLMSG_ALIGNTO and is fixed to 4 bytes. Therefore all netlink message headers, begin of payload sections, protocol specific headers, and attribute sections must start at an offset which is a multiple of NLMSG_ALIGNTO.

This is a low priority issue for my use case since being aware of it means you can use a simple workaround. (Just use `new_binary_payload` and append whatever 0's are necessary.)

In my specific usage (with neli 0.3.1), I was calling `new_nl_payload` and passing a `u16`. Including this attribute caused all further attributes to be improperly parsed by the kernel since this attribute was 6 bytes. Appending 2 bytes (to get to 8) fixed the problem.

**Comment by jbaublitz** [comment] 2019-04-29 23:35
Hi Brandon, not a problem. I'd rather know when things aren't working as expected. Currently bumping into some issues around how I solved stateful size calculations with regards to #15. I'm going to finish that up soon and after that will prioritize this. Thanks!

**Comment by jbaublitz** [comment] 2019-04-30 11:02
Hi Brandon, I've bumped into a situation where I actually need to solve this before the multiple message issue #15! The problem boils down to this. To handle multiple messages, I've needed to rework the traits a bit to be more flexible around how size is hinted when deserializing so that `Vec`s can be properly hinted and do not consume the rest of the buffer. These two problems are actually tightly coupled and I'm going to start with this one so that my trait architecture is flexible enough for all the uses cases it needs to cover. I need to support two use cases currently:
* deserializing structs that contain string identifiers represented by C types like `char[]` which translates into a Rust struct with `&'a str` or at least `String` - these should not be padded, only the whole struct should be padded to fit alignment 
* deserializing `String`/`u16` payloads and other types that need to be padded as, on their own, they do  not meet the 4 byte alignment
I originally didn't think of the first use case until I dug into some ACPI event netlink stuff and realized that if that case is not handled, neli will assume all strings are padded, even in the context of a struct which causes netlink errors when constructing messages. My initial thought on how to solve this in the general case in a better way than the case by case approach I took previously is to create an `NlPadding` type that is placed at the end of structs that need proper alignment. Not every type processed by neli is guaranteed to need it in every single circumstance so this would allow the user to essentially mark a struct as needing proper alignment when deserializing. It would also provide serialization with a way to understand that the padding should be discarded when converting it into a Rust representation. How does that sound to you?

**Comment by gluxon** [comment] 2019-04-30 18:20
> I originally didn't think of the first use case until I dug into some ACPI event netlink stuff and realized that if that case is not handled, neli will assume all strings are padded, even in the context of a struct which causes netlink errors when constructing messages.

That's weird. To make sure I'm understanding you correctly, you're saying some ACPI event netlink messages require padding strings within structs? Where the entire struct is a Netlink attribute and the string is not (an attribute)? I think I might be misreading the above since it contradicts the first bullet point.

> It would also provide serialization with a way to understand that the padding should be discarded when converting it into a Rust representation. How does that sound to you?

I may not have fully understood this either. I may be missing something, but is the following strategy enough to cover all cases?

- During serialization of an attribute, determine length as we currently do, but add `len % 4` null bytes to the payload vector.
- During deserialization, read the attribute len, consume `len + len % 4` bytes from the buffer, and run `len` bytes through the Nl type deserialize method.

From what I've seen, the `len` property of an attribute header is the unpadded length. If this isn't universally true, I can see this being significantly harder.

**Comment by gluxon** [comment] 2019-04-30 18:59
> > I originally didn't think of the first use case until I dug into some ACPI event netlink stuff and realized that if that case is not handled, neli will assume all strings are padded, even in the context of a struct which causes netlink errors when constructing messages.
>
> That's weird. To make sure I'm understanding you correctly, you're saying some ACPI event netlink messages require padding strings within structs? Where the entire struct is a Netlink attribute and the string is not (an attribute)? I think I might be misreading the above since it contradicts the first bullet point.

Nevermind, I see what you meant. You were saying that the library currently assumes that strings within structs are padded, but this typically isn't the case.

> My initial thought on how to solve this in the general case in a better way than the case by case approach I took previously is to create an NlPadding type that is placed at the end of structs that need proper alignment.

Hm.. to elaborate on my comment above, I don't know if an explicit `NlPadding` type (following the payload) is necessary since `len` is the unpadded size. I suppose it doesn't hurt to do though.

**Comment by jbaublitz** [comment] 2019-04-30 21:27
I was just about to get back to you and try to reword but I think we're on the same page now! I guess my idea with explicitly mentioning whether a struct should be padded or not came from my learning curve dealing with netlink. I had a lot of unfortunate encounters with padding bugs when first writing this library so I wanted to make it a little more readable to the user. However, I just finished discussing Linux struct alignment/memory mechanics with some people who are more familiar with those details than I am and it seems it might make sense to simply add the padding to the payloads instead of tying myself in knots trying to address the "padding or no padding" problem at the struct field level instead of the struct level. I'll see how that works and will report back with the results. For now, I think you're right that the padding handling can be implicit in the serialization/deserialization methods for the struct that contains the payload instead of in the `Vec`/`String`/etc. serialization/deserialization methods themselves. In retrospect, that doesn't make a lot of sense.

**Comment by jbaublitz** [comment] 2019-05-03 20:46
Just made a very big commit that should help fix some problems with the way that I designed the traits themselves. It is a breaking change but I think it will make my life and the life of developers using the library a lot easier. 8904c9edcec2899c93320d51f4b455895b63fffe fixes some things that have made me kinda tie myself in knots while writing this through changes to [buffering](https://github.com/jbaublitz/buffering) and reworking the `Nl` trait by breaking it into `Nl` and `NlBuf` traits, removing the need for `Nl::{serialize_with,deserialize_with}`. Thank you for working with me on this. I know this is taking longer than I expected and hope that the resulting code will make maintenance moving forward a lot easier.

**Comment by gluxon** [comment] 2019-05-07 00:39
> Just made a very big commit that should help fix some problems with the way that I designed the traits themselves. It is a breaking change but I think it will make my life and the life of developers using the library a lot easier.

Cool stuff! Thanks for the update.

> Thank you for working with me on this. I know this is taking longer than I expected and hope that the resulting code will make maintenance moving forward a lot easier.

No worries! Take your time. I appreciate that you're doing this at all.

**Comment by jbaublitz** [comment] 2019-05-09 00:18
I think I've fixed this! I'm pushing this to the same branch as #15.

**Comment by jbaublitz** [comment] 2019-05-10 15:15
No rush, of course but lemme know on this issue and the multiple messages issue if either or both have been resolved. I've rebased my rtnetlink work onto this branch because of some fundamental design changes these two issues required. I will keep working off of the `rtnl-dev` branch but I'll leave `multi-msg-feature` unmerged for now so I can add anything else you may need before closing these. Thanks!

**Comment by gluxon** [comment] 2019-05-11 20:56
> No rush, of course but lemme know on this issue and the multiple messages issue if either or both have been resolved.

The changes you've made work really well for multiple messages! Thanks.

I have yet to do some padding tests. I'll respond again once I do that.

**Comment by jbaublitz** [comment] 2019-05-11 22:44
Okay sounds good! Glad to hear it's working on your end.

**Comment by gluxon** [comment] 2019-05-12 19:56
So on the `multi-msg-feature` branch, following snippet:

```rust
use neli::nlattr::Nlattr;

fn main() {
    let payload = Nlattr::new_nl_payload::<u16>(None, 1, 3).unwrap();
    println!("{:#?}", payload);
}
```

currently prints out

```rust
Nlattr {
    nla_len: 8,
    nla_type: 1,
    payload: [
        3,
        0,
        0,
        0,
    ],
}
```

I believe `nla_len` should be `6`. `4` bytes for the header plus `2` bytes for the `u16`. From looking at genl ctrl, padding doesn't seem to be counted as a part of the length.

I haven't found any Linux documentation explicitly stating that `nla_len` doesn't count padding, but libnl's `nla_len` doesn't count padding either.

> nla_len() will return the length of the payload not including eventual padding bytes.
> http://www.infradead.org/~tgr/libnl/doc/core.html#_parsing_a_message

http://www.infradead.org/~tgr/libnl/doc/api/group__attr.html#gac5a7705797946fa9c0775997bb8d130b

**Comment by jbaublitz** [comment] 2019-05-13 15:23
You're absolutely right on this. I missed this and I see where the problem is: I added padding to the payload in the function `::new_nl_payload` which breaks `.size()`. This should only be done in the `.serialize()` function for `Nlattr` because only that function should handle alignment. I'm making those changes now. Thanks for catching this.

**Comment by jbaublitz** [comment] 2019-05-13 17:13
I'm just pushed tests as well to make sure I don't break this moving forward. I had removed tests for this during module refactoring and realized I should rewrite them.

**Comment by jbaublitz** [comment] 2019-05-18 01:17
I'm going to merge `multi-msg-feature` and close this. Feel free to comment here if it's not resolved and I'll reopen. Thanks!

**Closed by jbaublitz** 2019-05-18 01:17 UTC
