### ISSUE TITLE
Always add NlmF::Request as default behaviour (or if no flags are present) because Kernel requires it and libnl does it too

### ISSUE THREAD

**Issue by phip1611** [jbaublitz/neli#133] opened 2021-02-14 07:53 UTC
`Nlmsghdr::new()` takes field `nl_flags: NlmFFlags` which can be initialized like this: `NlmFFlags::new(&[NlmF::Request]),`. If the provided array is empty, i.e. `REQUEST (0x1)` is NOT present, the kernel rejects the request and doesn't forward it to the callback inside the kernel. Kernel reference: https://elixir.bootlin.com/linux/latest/source/net/netlink/af_netlink.c#L2487
This can result in a deadlock (socket/send never returns) in userland if the application waits for a reply in a blocking way.

`libnl`, the de facto standard library for netlink in C, also adds this flag automatically on each request: https://github.com/thom311/libnl/blob/2abeec851e4c748effac341f8db0b42389b37790/lib/nl.c#L489 

My suggestion:
- A: either add `NlmF::Request` always because there should be no usecase where the user doesn't want to send this flag, or
- B: make this an Option. If  `None` is provided it should be replaced with `NlmFFlags::new(&[NlmF::Request])`
- C: make this an Option and always add `NlmF::Request` as default flag (whether its None or Some) 

I prefer A or C because `neli` should help the user to make no mistakes at all.

PS: If you give me your ok, I can prepare this and create a PR.

**Comment by jbaublitz** [comment] 2021-02-14 11:58
This one is a little bit complicated because netlink can also be used for IPC between processes in userspace. Let me do some tests for this because theoretically someone could also be using `send` from a userspace process to return a response for the request and in this case, `NlmF::Request` should not be set. My initial reaction is that this is better addressed by #104 where we can clearly differentiate between requests and responses. `send` is by design meant to be a lower level protocol anyway.

**Comment by phip1611** [comment] 2021-02-14 13:40
I see, it would make sense there @jbaublitz. But what do you think about the following solution. You know if a socket targets the kernel when `NlSocketHandle` was created with destination `pid==0`. Wouldn't it make sense to check in `send` if destination `pid==0` and add the flag `NlmF::Request` in that case?

If you implement the presence of this flag on a higher level (request module) then there's always the danger that some developer uses his own abstractions along with neli's low level `send` - in that case there is no guarantee for the presence of flag `NlmF::Request`.

In any way: I think it would be useful for developers to note at some point in the neli doc comments that this flag is mandatory for kernel requests. Either in the doc comments of the flags itself, in send or in your upcoming request module.

**Comment by jbaublitz** [comment] 2021-02-14 13:49
I'm happy to add documentation, but the point of the lower level API is to give developers complete control over the implementation details. Each layer of abstraction does a little bit more management than the last so I still think that if people are using the lower level API, they will have to do a little bit more reading on netlink and if they use the higher level API, I can manage it for them. The lower level API is meant to support all use cases while the higher level API is targeted towards specific use cases that may not be sufficient for everyone.

Just to give you an example, `NlSocket` does basically no management for the user. `NlSocketHandle` is able to handle `NlmF::Ack` responses, `Nlmsg::Error` messages, `NlmF::Multi` messages, and all of those kinds of workflows simply because this is a requirement for every netlink use case to follow. However, anything that is not generic to every workflow needs to go up one level of abstraction (like `nl_seq` handling for example as this varies between multicast subscription workflows and request-response workflows for example). I believe this is the same for `NlmF::Request`.

If you would like to put up a PR for the documentation for now, I'm happy to make a note in #20 to support this use case for the higher level API.

**Comment by phip1611** [comment] 2021-02-15 15:41
I'm not sure what would be a good place for documentation on this specific topic. I'd love to write a comment directly on `NlmF::Request` but because you generate the enum by macro (`src/consts/nl.rs` => 
```
impl_var!(
    /// Values for `nl_flags` in [`Nlmsghdr`][crate::nl::Nlmsghdr]
    pub NlmF, u16,`
```
) instead of doing it "statically"/"typically", it's not possible to add doc comments on specific fields. I could extend the comment 
```
/// Values for `nl_flags` in [`Nlmsghdr`][crate::nl::Nlmsghdr]
```
but this doesn't show up on **docs.rs** -  only in IDEs that are smart enough to extract doc comments from macro expansion. Do you have a good idea how/where to add more documentation on this in a sensible way?

**Comment by phip1611** [comment] 2021-02-17 10:08
To workaround the problem with doc comments I mentioned in the previous reply:

What do you think about the idea of the following, breaking refactoring for a future release:
Declare enums like `NlmF` again in the classic way and implement the traits with a procedural macro. Like this:
```
#[neli:impl_var]
/// Doc comment.
pub enum NlmF {
    /// Doc comments would work again.
    Request => libc::NLM_F_REQUEST as u16,
    // ...
}
```
This would require a new `neli-codegen` package as dependency of `neli`. If you are interested in this, we could open a new issue for new a future, major(=breaking) release. 

I understand why you took the macro approach and it's good for less code duplication but I think it's a little bit unfortunate that this way there can't be good doc comments on docs.rs

**Comment by jbaublitz** [comment] 2021-02-18 13:20
This can actually be solved using declarative macros without the need for procedural macros. Let me see if I can put up a PR and get your feedback on it.

**Comment by jbaublitz** [comment] 2021-11-18 22:03
@phip1611 Now that 0.6.0 is out, I think we can add in the documentation for NlmF::Request more easily.

**Closed** 2022-03-24 02:22 UTC
Labels: enhancement
