### ISSUE TITLE
Creating nested attributes

### ISSUE THREAD

**Issue by manuels** [jbaublitz/neli#21] opened 2019-05-31 15:12 UTC
A while ago this library had a `NlAttrHdr::new_nested()` function but it seems to be removed.
Is there an alternative function to create nested attributes?

**Comment by jbaublitz** [comment] 2019-06-02 21:40
Hi @manuels, as you noticed, there were some breaking changes in `v0.4.0`. As I was unable to release the version due to a `libc` PR, I am open to including some changes before release. I think the issue here boils down to the way `Genlmsghdr` attributes are structured, is that correct? `Genlmsghdr`s require a vector of attributes which now cannot easily be created as nested attributes. If this is indeed the problem you're referring to, it's oversight on my part and I can add that function in again as deserializing attributes was given more attention during this release process than serializing. Does that sound good?

**Comment by jbaublitz** [comment] 2019-06-03 19:35
Hi @manuels, after reviewing my changes I realized that there is already a new way to do this. I originally thought there was but got tripped up by the type `impl`s before writing my previous comment. I've uploaded an example of how to do this moving forward in the `examples/` directory. The code is in the file `create-nested-attributes.rs`. I'm going to close this but please comment back and I'll reopen if you run into any issues.

**Comment by manuels** [comment] 2019-06-03 19:54
Thanks, I'll give it a try.

**Comment by jbaublitz** [comment] 2019-06-03 21:52
No problem. Please do post back here if you run into type checking issues. Given vectors cannot have heterogeneous types, I can make some changes to some of the type definitions to allow heterogeneous trait object-based vectors if necessary. I do think this should work though as vectors of attributes should all have the same type for both the payload and type fields of the struct.

**Comment by manuels** [comment] 2019-06-04 16:44
Hi @jbaublitz, I gave it a try, but nesting like this does not work:

```
        let attrs = vec![
            Nlattr::new(None, 1, vec![
                Nlattr::new(None, 1, "this_family"),
                Nlattr::new(None, 2, 0), // <-- expected &str, found integer !!!
            ]),
            Nlattr::new(None, 2, vec![
                Nlattr::new(None, 1, "this_family"),
                Nlattr::new(None, 2, 0),
            ])
        ];
```

(I want to communicate to wireguard: https://github.com/WireGuard/WireGuard/blob/master/src/uapi/wireguard.h#L32)

**Comment by jbaublitz** [comment] 2019-06-04 17:18
Reopening. I'll see what I can do to fix this and will push `v0.4.1` once you've confirmed that you're able to create attributes without an error. For now, you can serialize attributes one by one into a buffer, but that is definitely not the workflow I want to provide for vectors of attributes moving forward.

**Comment by jbaublitz** [comment] 2019-06-10 14:45
@manuels I have pushed a method to master and updated `examples/` to explain the two ways to do this, one for heterogeneous vectors and one for homogeneous vectors. Both are now possible. Please give that a try and let me know if I should do additional work before releasing `v0.4.1`.

**Comment by manuels** [comment] 2019-06-11 15:27
@jbaublitz, the new function looks great. The only problem that I am facing right now is that this does not work for `Nlmsghdr`.

```
        let mut p = Nlattr::new(None, 0, vec![]);
        p.add_nested_attribute(Nlattr::new(None, WGPEER_A_PUBLIC_KEY, key.to_vec()))?;
        p.add_nested_attribute(Nlattr::new(None, WGPEER_A_FLAGS, 0))?;
        p.add_nested_attribute(Nlattr::new(None, WGPEER_A_ENDPOINT, addr))?;

        let mut peers = Nlattr::new(None, WGDEVICE_A_PEERS, vec![]);
        peers.add_nested_attribute(p)?;

        let attrs = vec![
            Nlattr::new(None, WGDEVICE_A_IFINDEX, ifindex),
            Nlattr::new(None, WGDEVICE_A_FLAGS, 0),
            peers, // <-- expected u32, found struct `std::vec::Vec`
        ];
        let genlhdr = Genlmsghdr::new(WG_CMD_SET_DEVICE, self.version, attrs)?;
        let nlhdr = Nlmsghdr::new(None, self.family_id, vec![Request, Ack], None, None, genlhdr);
```

Maybe `Nlattr` could implement `neli::nlattr::Nlattr<_, std::vec::Vec<u8>>` for any payload type, so you could do

```
        let attrs = vec![
            Nlattr::new(None, WGDEVICE_A_IFINDEX, ifindex).into(),
            Nlattr::new(None, WGDEVICE_A_FLAGS, 0).into(),
            peers.into(),
        ];

```

**Comment by jbaublitz** [comment] 2019-06-11 20:35
@manuels Thanks for letting me know about this. This is indeed not ideal from a usability perspective. There are work-arounds for this but what I'd prefer to do is rethink `Nlattr` just a little bit. My instinct is to do the following:
* Leave `.add_nested_attribute()` as is with a bug fix for the missing needed additional type parameter
* Add `.set_payload()` to allow on `Nlattr<T, Vec<u8>>` to essentially serialize payloads immediately on invocation as opposed to delaying serializing the entire data structure at the end
* Change `Nlattr::new()` to only be available when `Nlattr<T, Vec<u8>>` is used and have `::new()` call `.set_payload()` internally
* Change `Genlmsghdr` slightly to only accept attributes that have payloads represented as `Vec<u8>`

This is a relatively invasive change that is a result of me trying to support too many options for attribute parsing so I'm going to release this as `0.4.0-r1` as I do not think the previous way of doing things is a very good idea after thinking more on the use case you've presented. While I will leave the option to construct `Nlattr<T, P>`-typed attributes, I definitely want to push generic attribute parsing more in the direction of one way to construct vectors of attributes adhering more to a builder pattern.

I updated the examples to reflect the proposed way of handling this - please let me know if what I push to master is adequate for your use case. If so, I will release.

**Comment by jbaublitz** [comment] 2019-06-12 15:28
Just a note that I considered the idea of using the `Into` trait and appreciate the suggestion but it didn't seem quite as straightforward and I personally think this will make the learning curve slightly less steep for new users. I think one type of approach (more of a builder pattern here) will make it slightly more transparent while also at least providing some type safety up front at the attribute top level by parsing `Nlattr`s into a vector and providing payloads as bytes for further manipulation if needed. Let me know if you have any additional feedback and if the current way of doing things suits your needs.

**Comment by manuels** [comment] 2019-06-14 18:14
Hi @jbaublitz, the new functionality looks good so far. Thanks!

**Closed** 2019-06-15 14:00 UTC
